name: Build, Test, Naming Convention Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  # Build and Test
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build solution in Debug
        run: msbuild "Project5_HR/Project5_HR.sln" /p:Configuration=Debug /p:Platform=x64 /t:Build

      - name: Run unit tests
        run: |
          vstest.console.exe "Project5_HR/x64/Debug/Project5_HR_Test.dll"

# Check the naming convention
  clang-tidy-check:
    runs-on: ubuntu-latest 
    needs: [build-and-test]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Clang-Tidy Review (includes naming checks)
        uses: ZedThree/clang-tidy-review@v0.19.1 
        with:
          cmake_command: cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
          
          build_dir: build
          clang_tidy_checks: '-*,readability-identifier-naming,cppcoreguidelines-*'

          # Optional: Use this to get nicer annotations directly on the PR.
          token: ${{ secrets.GITHUB_TOKEN }}
